name: airacg-jdtask
on:
  schedule:
    - cron: '21 0-23/2 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-airacg-jdtask
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync airacg-jdtask
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/airacg/jd_task"
          source_branch: "main"
          destination_branch: "airacg-jdtask"
          github_token: ${{ secrets.PAT }}
