name: CloudMusic-LevelUp
on:
  schedule:
    - cron: '8 0-23/3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-curtinlv-JDScript
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync curtinlv-JDScript
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/curtinlv/JD-Script.git"
          source_branch: "main"
          destination_branch: "curtinlv-JDScript"
          github_token: ${{ secrets.PAT }}
